In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdfkit as pdf

In [2]:
prob_ = "signed_graphs"
n_ = 60

In [3]:
form_ = "edge3"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp3_n60 = pd.DataFrame()
lp3_n60 = pd.concat([lp3_n60, df], ignore_index=True)
lp3_n60.columns = ['instance','bs','time']
#lp3_n60

tab = pd.DataFrame({
    'instance':"lp3_default",
    'bs':lp3_n60['bs'].mean(),
    'time':lp3_n60['time'].mean()
    },index=[""]
)

lp3_n60 = pd.concat([lp3_n60,tab])
lp3_n60['instance'] = lp3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp3_n60

                              instance   bs    time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  1.5000
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  1.4300
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  1.7000
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  1.6100
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  1.4000
..                                 ...  ...     ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.6100
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.5000
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.5400
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.6600
                           lp3_default  0.0  0.9345

[61 rows x 3 columns]

In [4]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"mip3_default",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,23.0,0.000000,469.4200,28.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,11.0,0.000000,306.6100,7.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,9.0,0.000000,307.1600,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,13.0,0.000000,363.0100,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,13.0,0.000000,311.1600,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,13.0,0.410000,3600.0100,3552.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,13.0,0.410000,3600.6200,1778.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,13.0,0.500000,3600.0200,10202.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,12.0,0.540000,3600.0100,2307.000000,0
,mip3_default,23.75,17.0,0.173333,1592.4855,953.966667,38

In [5]:
mip3_n60['instance'] = mip3_n60['instance'].str.replace('_','\_') 
print(mip3_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 469.42 & 28.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 306.61 & 7.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 307.16 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 363.01 & 7.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 311.16 & 9.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 38.00 & 0.00 & 3037.56 & 1101.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 399.63 & 21.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 656.04 & 38.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 676.66 & 99.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 790.84 & 54.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 28.00 & 0.54 & 3600.06 & 692.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 30.00 & 0.45 & 3601.05 & 511.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 34.00 & 0.46 & 3600.04 & 358.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 20.00 & 0.70 & 3600.02 & 489.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 27.00 & 0.52 & 3601.99 & 387.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 149.60 & 9.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 267.25 & 25.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 236.98 & 38.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 296.08 & 17.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 118.06 & 5.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 503.61 & 110.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 637.47 & 201.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 469.53 & 90.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 1317.95 & 416.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 345.10 & 72.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 18.00 & 0.56 & 3600.08 & 957.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 20.00 & 0.43 & 3600.72 & 687.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 18.00 & 0.51 & 3600.01 & 1244.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 22.00 & 0.55 & 3600.46 & 669.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 14.00 & 0.66 & 3600.07 & 863.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 78.73 & 22.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 191.73 & 31.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 124.09 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 459.81 & 290.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 232.53 & 65.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 360.66 & 165.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 148.57 & 36.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 621.27 & 372.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 680.49 & 414.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 619.80 & 456.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 17.00 & 0.39 & 3600.77 & 1589.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 17.00 & 0.41 & 3600.42 & 1159.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 18.00 & 0.44 & 3600.96 & 1198.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 16.00 & 0.47 & 3600.01 & 1566.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 17.00 & 0.47 & 3600.01 & 1263.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 107.42 & 176.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 36.00 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 120.05 & 21.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 109.70 & 26.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 101.76 & 14.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 14.00 & 0.22 & 3600.01 & 2353.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 150.69 & 51.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 12.00 & 0.33 & 3600.02 & 14119.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 191.06 & 72.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 347.68 & 615.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 13.00 & 0.43 & 3600.01 & 4105.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 13.00 & 0.41 & 3600.01 & 3552.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 13.00 & 0.41 & 3600.62 & 1778.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 13.00 & 0.50 & 3600.02 & 10202.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 12.00 & 0.54 & 3600.01 & 2307.00 & 0 \\
mip3\_default & 17.00 & 0.17 & 1592.49 & 953.97 & 38 \\
\bottomrule
\end{tabular}

In [6]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"mip3_presolve0",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,1.0,0.960000,3600.140,735.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,2.0,0.820000,3600.030,710.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,2.0,0.780000,3600.030,717.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,0.0,1.000000,3600.020,90.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.0,0.920000,3600.020,714.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,23.000000,2.0,0.910000,3600.070,1362.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,2.0,0.910000,3600.000,3207.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,2.0,0.920000,3600.030,1604.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,27.000000,2.0,0.930000,3600.040,1164.000000,0
,mip3_presolve0,24.833333,1.5,0.883167,3547.032,1803.433333,1

In [7]:
mip3_n60['instance'] = mip3_n60['instance'].str.replace('_','\_') 
print(mip3_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 1.00 & 0.96 & 3600.14 & 735.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 2.00 & 0.82 & 3600.03 & 710.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 2.00 & 0.78 & 3600.03 & 717.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 0.00 & 1.00 & 3600.02 & 90.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 1.00 & 0.92 & 3600.02 & 714.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 0.00 & 1.00 & 3600.06 & 422.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 0.00 & 1.00 & 3600.02 & 388.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 0.00 & 1.00 & 3600.02 & 208.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 0.00 & 1.00 & 3600.01 & 167.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 0.00 & 1.00 & 3600.01 & 264.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 0.00 & 1.00 & 3600.05 & 307.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 0.00 & 1.00 & 3600.01 & 239.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 0.00 & 1.00 & 3600.02 & 162.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 0.00 & 1.00 & 3600.01 & 284.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 0.00 & 1.00 & 3600.01 & 102.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 2.00 & 0.85 & 3600.04 & 1916.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 2.00 & 0.78 & 3600.07 & 1160.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 2.00 & 0.86 & 3600.04 & 1205.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 2.00 & 0.87 & 3600.11 & 713.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 2.00 & 0.75 & 3600.01 & 2710.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 1.00 & 0.95 & 3600.01 & 1187.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 1.00 & 0.95 & 3600.01 & 874.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 1.00 & 0.95 & 3600.01 & 1132.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 0.00 & 1.00 & 3600.01 & 593.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 2.00 & 0.89 & 3600.02 & 672.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 1.00 & 0.98 & 3600.04 & 634.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 1.00 & 0.97 & 3600.01 & 662.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 2.00 & 0.95 & 3600.02 & 703.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 0.00 & 1.00 & 3600.01 & 324.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 1.00 & 0.97 & 3600.02 & 655.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 2.00 & 0.78 & 3600.01 & 2017.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 3.00 & 0.57 & 3600.06 & 8407.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 2.00 & 0.78 & 3600.01 & 1567.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 2.00 & 0.88 & 3600.01 & 1676.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 2.00 & 0.85 & 3600.01 & 2408.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 2.00 & 0.88 & 3600.01 & 1540.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 2.00 & 0.85 & 3600.02 & 1850.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 2.00 & 0.89 & 3600.01 & 1373.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 1.00 & 0.95 & 3600.04 & 1087.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 1.00 & 0.94 & 3600.01 & 895.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 2.00 & 0.93 & 3600.05 & 933.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 2.00 & 0.93 & 3600.01 & 1124.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 2.00 & 0.94 & 3600.01 & 1012.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 2.00 & 0.93 & 3600.06 & 1011.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 2.00 & 0.94 & 3600.01 & 885.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 5.00 & 0.55 & 3600.01 & 14725.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 420.37 & 4912.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 2.00 & 0.80 & 3600.05 & 4388.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 2.00 & 0.80 & 3600.01 & 5208.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 2.00 & 0.67 & 3600.01 & 4863.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 2.00 & 0.89 & 3600.01 & 4926.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 2.00 & 0.83 & 3600.01 & 2145.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 2.00 & 0.89 & 3600.06 & 3842.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 2.00 & 0.86 & 3600.00 & 3707.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 2.00 & 0.87 & 3600.03 & 1694.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 2.00 & 0.92 & 3600.00 & 2025.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 2.00 & 0.91 & 3600.07 & 1362.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 2.00 & 0.91 & 3600.00 & 3207.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 2.00 & 0.92 & 3600.03 & 1604.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 2.00 & 0.93 & 3600.04 & 1164.00 & 0 \\
mip3\_presolve0 & 1.50 & 0.88 & 3547.03 & 1803.43 & 1 \\
\bottomrule
\end{tabular}

In [8]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"mip3_eqcon2_default",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.00,0.0000,598.280000,37.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.00,0.0000,411.680000,11.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.00,0.0000,337.790000,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.00,0.0000,385.420000,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.00,0.0000,416.310000,11.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,11.00,0.5000,3600.010000,1039.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,16.00,0.2700,3600.660000,1568.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,12.00,0.5400,3600.010000,3673.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,13.00,0.5000,3600.040000,1231.000000,0
,mip3_eqcon2_default,24.066667,16.25,0.1895,1820.657167,924.116667,38

In [9]:
mip3_n60['instance'] = mip3_n60['instance'].str.replace('_','\_') 
print(mip3_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 598.28 & 37.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 411.68 & 11.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 337.79 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 385.42 & 7.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 416.31 & 11.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 31.00 & 0.18 & 3600.44 & 820.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 830.93 & 82.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 1253.20 & 48.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 2162.81 & 139.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 1322.15 & 93.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 17.00 & 0.77 & 3600.53 & 454.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 29.00 & 0.47 & 3600.02 & 411.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 24.00 & 0.62 & 3600.02 & 298.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 21.00 & 0.70 & 3600.17 & 278.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 23.00 & 0.57 & 3600.48 & 330.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 184.57 & 13.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 364.30 & 11.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 323.94 & 72.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 559.47 & 41.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 202.49 & 13.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 673.71 & 117.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 2183.44 & 468.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 1677.70 & 1092.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 1963.10 & 443.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 874.08 & 318.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 17.00 & 0.61 & 3600.01 & 685.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 20.00 & 0.43 & 3600.02 & 918.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 15.00 & 0.61 & 3600.90 & 813.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 16.00 & 0.68 & 3600.02 & 491.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 14.00 & 0.62 & 3600.01 & 945.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 138.63 & 35.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 229.06 & 51.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 171.88 & 11.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 572.01 & 190.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 481.83 & 148.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 997.89 & 1240.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 196.70 & 52.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 1023.09 & 277.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 2644.71 & 1871.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 676.93 & 135.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 18.00 & 0.36 & 3600.01 & 1230.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 18.00 & 0.38 & 3600.04 & 1331.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 13.00 & 0.59 & 3600.04 & 1246.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 16.00 & 0.52 & 3600.02 & 917.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 15.00 & 0.53 & 3601.13 & 857.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 240.54 & 945.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 32.30 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 154.32 & 38.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 130.88 & 21.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 116.99 & 13.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 10.00 & 0.44 & 3600.01 & 8314.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 340.78 & 139.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 18.00 & 0.00 & 2501.46 & 14409.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 538.67 & 951.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 2120.79 & 1282.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 12.00 & 0.48 & 3600.01 & 2764.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 11.00 & 0.50 & 3600.01 & 1039.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 16.00 & 0.27 & 3600.66 & 1568.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 12.00 & 0.54 & 3600.01 & 3673.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 13.00 & 0.50 & 3600.04 & 1231.00 & 0 \\
mip3\_eqcon2\_default & 16.25 & 0.19 & 1820.66 & 924.12 & 38 \\
\bottomrule
\end{tabular}

In [10]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"mip3_eqcon2_presolve0",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,0.000000,1.000000,3600.010000,97.00,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,2.000000,0.820000,3600.020000,697.00,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,1.000000,0.890000,3600.020000,674.00,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,0.000000,1.000000,3600.050000,679.00,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,0.000000,1.000000,3600.020000,613.00,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,2.000000,0.910000,3600.040000,935.00,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,2.000000,0.910000,3600.010000,1738.00,0
58,random_n60_k5_pos30_neg5_err20_4.g,27.000000,2.000000,0.930000,3600.010000,1575.00,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,2.000000,0.920000,3600.010000,998.00,0
,mip3_eqcon2_presolve0,25.966667,1.233333,0.897667,3548.224167,1201.05,1

In [11]:
mip3_n60['instance'] = mip3_n60['instance'].str.replace('_','\_') 
print(mip3_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 0.00 & 1.00 & 3600.01 & 97.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 2.00 & 0.82 & 3600.02 & 697.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 1.00 & 0.89 & 3600.02 & 674.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 0.00 & 1.00 & 3600.05 & 679.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 0.00 & 1.00 & 3600.02 & 613.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 0.00 & 1.00 & 3600.02 & 102.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 0.00 & 1.00 & 3600.02 & 342.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 0.00 & 1.00 & 3600.01 & 107.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 0.00 & 1.00 & 3600.03 & 151.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 0.00 & 1.00 & 3600.02 & 100.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 0.00 & 1.00 & 3600.01 & 153.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 0.00 & 1.00 & 3600.02 & 119.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 0.00 & 1.00 & 3600.01 & 81.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 0.00 & 1.00 & 3600.02 & 85.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 0.00 & 1.00 & 3600.01 & 134.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 2.00 & 0.85 & 3600.05 & 1939.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 2.00 & 0.78 & 3600.08 & 996.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 2.00 & 0.86 & 3600.01 & 1144.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 0.00 & 1.00 & 3600.01 & 308.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 2.00 & 0.75 & 3600.07 & 1536.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 0.00 & 1.00 & 3600.08 & 576.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 1.00 & 0.95 & 3600.02 & 663.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 1.00 & 0.95 & 3600.01 & 644.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 0.00 & 1.00 & 3600.01 & 391.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 0.00 & 1.00 & 3600.06 & 541.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 0.00 & 1.00 & 3600.01 & 443.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 0.00 & 1.00 & 3600.01 & 417.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 0.00 & 1.00 & 3600.01 & 555.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 0.00 & 1.00 & 3600.01 & 288.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 0.00 & 1.00 & 3600.12 & 563.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 2.00 & 0.78 & 3600.04 & 1396.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 2.00 & 0.71 & 3600.03 & 3135.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 2.00 & 0.78 & 3600.01 & 1001.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 2.00 & 0.88 & 3600.04 & 1630.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 2.00 & 0.85 & 3600.04 & 1195.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 1.00 & 0.94 & 3600.02 & 1032.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 2.00 & 0.85 & 3600.05 & 1142.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 2.00 & 0.89 & 3600.03 & 836.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 1.00 & 0.95 & 3600.01 & 775.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 2.00 & 0.89 & 3600.06 & 681.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 0.00 & 1.00 & 3600.04 & 637.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 2.00 & 0.93 & 3600.04 & 854.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 2.00 & 0.94 & 3600.01 & 882.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 2.00 & 0.94 & 3600.05 & 904.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 2.00 & 0.94 & 3600.05 & 665.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 5.00 & 0.55 & 3600.03 & 10085.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 491.74 & 5329.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 2.00 & 0.80 & 3600.04 & 2062.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 2.00 & 0.80 & 3600.00 & 3804.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 2.00 & 0.67 & 3600.01 & 2030.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 2.00 & 0.89 & 3600.01 & 3162.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 2.00 & 0.83 & 3600.05 & 1515.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 2.00 & 0.89 & 3600.03 & 2112.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 2.00 & 0.85 & 3600.05 & 2091.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 2.00 & 0.87 & 3600.01 & 1293.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 2.00 & 0.92 & 3600.04 & 1431.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 2.00 & 0.91 & 3600.04 & 935.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 2.00 & 0.91 & 3600.01 & 1738.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 2.00 & 0.93 & 3600.01 & 1575.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 2.00 & 0.92 & 3600.01 & 998.00 & 0 \\
mip3\_eqcon2\_presolve0 & 1.23 & 0.90 & 3548.22 & 1201.05 & 1 \\
\bottomrule
\end{tabular}