In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdfkit as pdf

In [30]:
prob_ = "signed_graphs"
n_ = 60

In [31]:
form_ = "edge1"
method_ = "lp"

file=f"edge1/{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp1_n60 = pd.DataFrame()
lp1_n60 = pd.concat([lp1_n60, df], ignore_index=True)
lp1_n60.columns = ['instance','bs','time']
#lp1_n60

tab = pd.DataFrame({
    'instance':"lp_default",
    'bs':lp1_n60['bs'].mean(),
    'time':lp1_n60['time'].mean()
    },index=[""]
)

lp1_n60 = pd.concat([lp1_n60,tab])
lp1_n60['instance'] = lp1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp1_n60

                              instance   bs   time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  0.060
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  0.050
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  0.060
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  0.060
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  0.050
..                                 ...  ...    ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.030
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.030
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.030
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.030
                            lp_default  0.0  0.039

[61 rows x 3 columns]

In [32]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.00,0.000000,11.0400,81.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.00,0.000000,1.6300,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.00,0.000000,4.5800,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.00,0.000000,13.3900,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.00,0.000000,5.8700,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.00,0.000000,136.7300,4677.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.00,0.000000,228.0900,15647.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.00,0.000000,914.6500,37768.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.00,0.000000,467.8300,16214.000000,1
,mip1_default,23.616667,22.35,0.022833,541.8275,6931.783333,54

In [33]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 11.04 & 81.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 1.63 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 4.58 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 13.39 & 7.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 5.87 & 9.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 38.00 & 0.00 & 35.94 & 468.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 4.89 & 15.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 30.02 & 70.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 23.35 & 134.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 10.73 & 66.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 44.00 & 0.28 & 3600.00 & 17707.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 53.00 & 0.00 & 750.35 & 4883.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 56.00 & 0.11 & 3600.00 & 15352.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 45.00 & 0.33 & 3600.01 & 13787.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 46.00 & 0.15 & 3600.00 & 12644.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 0.92 & 7.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 2.54 & 7.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 1.71 & 19.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 4.27 & 18.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 1.92 & 5.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 4.70 & 170.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 2.08 & 55.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 7.15 & 203.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 24.81 & 416.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 3.12 & 74.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 41.00 & 0.00 & 1984.42 & 35689.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 35.00 & 0.00 & 404.75 & 6015.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 37.00 & 0.00 & 1149.68 & 25188.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 34.00 & 0.31 & 3600.00 & 22806.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 30.00 & 0.19 & 3600.00 & 51197.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 1.09 & 32.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 1.19 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 1.22 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 3.54 & 136.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 1.99 & 36.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 3.32 & 159.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 2.17 & 27.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 7.95 & 253.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 3.99 & 123.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 3.29 & 108.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 28.00 & 0.00 & 433.73 & 11911.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 29.00 & 0.00 & 490.37 & 18293.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 32.00 & 0.00 & 1110.89 & 32811.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 30.00 & 0.00 & 1244.75 & 29040.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 32.00 & 0.00 & 1106.17 & 24807.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 2.22 & 121.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 1.13 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 1.64 & 29.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 1.45 & 21.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 1.63 & 14.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 18.00 & 0.00 & 25.76 & 1564.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 2.15 & 77.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 18.00 & 0.00 & 23.38 & 2331.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 2.36 & 77.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 4.08 & 175.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 23.00 & 0.00 & 197.02 & 12337.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 22.00 & 0.00 & 136.73 & 4677.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 22.00 & 0.00 & 228.09 & 15647.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 26.00 & 0.00 & 914.65 & 37768.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 26.00 & 0.00 & 467.83 & 16214.00 & 1 \\
mip1\_default & 22.35 & 0.02 & 541.83 & 6931.78 & 54 \\
\bottomrule
\end{tabular}

In [34]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,3.000000,0.870000,3600.000000,4085.00,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,4.000000,0.640000,3600.000000,4220.00,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,3.000000,0.670000,3600.000000,3293.00,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,3.000000,0.770000,3600.000000,3422.00,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,3.000000,0.770000,3600.000000,4572.00,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,4.000000,0.820000,3600.000000,26375.00,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,4.000000,0.820000,3600.000000,31778.00,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,4.000000,0.850000,3600.000000,41100.00,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,4.000000,0.850000,3600.000000,16679.00,0
,mip1_presolve0,23.65,3.866667,0.734333,3505.155667,30588.45,3

In [35]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 3.00 & 0.87 & 3600.00 & 4085.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 4.00 & 0.64 & 3600.00 & 4220.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 3.00 & 0.67 & 3600.00 & 3293.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 3.00 & 0.77 & 3600.00 & 3422.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 3.00 & 0.77 & 3600.00 & 4572.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 3.00 & 0.92 & 3600.00 & 5171.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 4.00 & 0.83 & 3600.00 & 6253.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 3.00 & 0.91 & 3600.00 & 2779.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 3.00 & 0.91 & 3600.00 & 3100.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 2.00 & 0.92 & 3600.00 & 2634.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 2.00 & 0.97 & 3600.00 & 3992.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 3.00 & 0.94 & 3600.00 & 4991.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 3.00 & 0.95 & 3600.00 & 2432.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 3.00 & 0.96 & 3600.00 & 2793.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 2.00 & 0.96 & 3600.00 & 2801.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 3.00 & 0.77 & 3600.00 & 62459.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 5.00 & 0.44 & 3600.00 & 49405.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 4.00 & 0.71 & 3600.00 & 29428.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 3.00 & 0.80 & 3600.00 & 6745.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 6.00 & 0.25 & 3600.00 & 33217.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 3.00 & 0.86 & 3600.00 & 13013.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 3.00 & 0.85 & 3600.00 & 12979.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 4.00 & 0.80 & 3600.00 & 20841.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 3.00 & 0.89 & 3600.00 & 7799.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 4.00 & 0.79 & 3600.00 & 14779.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 4.00 & 0.90 & 3600.00 & 15254.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 2.00 & 0.94 & 3600.00 & 10164.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 3.00 & 0.92 & 3600.00 & 14034.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 2.00 & 0.96 & 3600.00 & 6844.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 3.00 & 0.92 & 3600.00 & 11023.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 5.00 & 0.44 & 3600.00 & 32802.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 3292.94 & 130909.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 5.00 & 0.44 & 3600.00 & 33031.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 4.00 & 0.75 & 3600.00 & 36670.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 5.00 & 0.62 & 3600.00 & 88730.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 5.00 & 0.71 & 3600.00 & 47149.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 6.00 & 0.54 & 3600.00 & 94777.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 3.00 & 0.84 & 3600.00 & 16408.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 4.00 & 0.80 & 3600.00 & 18171.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 5.00 & 0.72 & 3600.00 & 20194.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 3.00 & 0.89 & 3600.00 & 18394.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 3.00 & 0.90 & 3600.00 & 17061.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 3.00 & 0.91 & 3600.00 & 16874.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 3.00 & 0.90 & 3600.00 & 16286.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 5.00 & 0.84 & 3600.00 & 19040.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 6.00 & 0.45 & 3600.00 & 173485.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 93.28 & 11213.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 5.00 & 0.50 & 3600.00 & 73544.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 5.00 & 0.50 & 3600.00 & 79858.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 1723.12 & 45769.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 4.00 & 0.78 & 3600.00 & 111012.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 6.00 & 0.50 & 3600.00 & 37859.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 4.00 & 0.78 & 3600.00 & 35852.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 5.00 & 0.62 & 3600.00 & 72322.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 5.00 & 0.67 & 3600.00 & 48854.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 4.00 & 0.83 & 3600.00 & 58589.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 4.00 & 0.82 & 3600.00 & 26375.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 4.00 & 0.82 & 3600.00 & 31778.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 4.00 & 0.85 & 3600.00 & 41100.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 4.00 & 0.85 & 3600.00 & 16679.00 & 0 \\
mip1\_presolve0 & 3.87 & 0.73 & 3505.16 & 30588.45 & 3 \\
\bottomrule
\end{tabular}

In [36]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.000000,0.000000,22.600,76.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,12.080,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,3.910,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,17.050,3.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.000000,0.000000,17.110,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.000000,0.000000,157.310,4540.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.000000,0.000000,141.470,7924.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.000000,0.000000,450.980,16425.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.000000,0.000000,271.600,3721.000000,1
,mip1_eqcon2_default,23.616667,22.566667,0.017833,553.918,3961.533333,56

In [37]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 22.60 & 76.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 12.08 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 3.91 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 17.05 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 17.11 & 9.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 38.00 & 0.00 & 191.49 & 763.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 48.95 & 64.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 53.32 & 72.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 52.36 & 92.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 20.52 & 17.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 43.00 & 0.30 & 3600.00 & 8866.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 53.00 & 0.00 & 3209.03 & 8719.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 63.00 & 0.00 & 3115.87 & 6042.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 42.00 & 0.37 & 3600.00 & 7503.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 48.00 & 0.11 & 3600.00 & 9855.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 2.59 & 9.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 2.85 & 11.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 5.53 & 63.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 18.20 & 31.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 0.93 & 5.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 6.05 & 94.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 6.90 & 50.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 7.62 & 191.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 143.57 & 1013.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 5.52 & 84.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 41.00 & 0.00 & 1955.70 & 16554.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 35.00 & 0.00 & 1409.68 & 14703.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 37.00 & 0.00 & 1680.75 & 18115.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 35.00 & 0.29 & 3600.00 & 12791.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 37.00 & 0.00 & 1524.10 & 15231.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 1.67 & 27.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 3.22 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 4.45 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 6.16 & 172.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 2.79 & 58.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 4.46 & 70.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 2.20 & 31.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 12.97 & 194.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 6.80 & 118.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 9.77 & 99.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 28.00 & 0.00 & 506.02 & 8846.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 29.00 & 0.00 & 379.60 & 5194.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 32.00 & 0.00 & 605.24 & 15411.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 30.00 & 0.00 & 871.41 & 13438.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 32.00 & 0.00 & 1254.02 & 18226.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 1.84 & 54.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 1.19 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 2.79 & 27.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 1.41 & 20.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 3.19 & 12.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 18.00 & 0.00 & 20.16 & 973.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 1.66 & 74.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 18.00 & 0.00 & 45.26 & 2314.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 3.87 & 113.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 7.09 & 91.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 23.00 & 0.00 & 520.20 & 18467.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 22.00 & 0.00 & 157.31 & 4540.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 22.00 & 0.00 & 141.47 & 7924.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 26.00 & 0.00 & 450.98 & 16425.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 26.00 & 0.00 & 271.60 & 3721.00 & 1 \\
mip1\_eqcon2\_default & 22.57 & 0.02 & 553.92 & 3961.53 & 56 \\
\bottomrule
\end{tabular}

In [38]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"mip1_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,3.00,0.8700,3600.000000,3431.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,3.00,0.7300,3600.000000,3328.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,4.00,0.5600,3600.000000,3039.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,3.00,0.7700,3600.000000,2321.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,2.00,0.8500,3600.000000,2795.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,3.00,0.8600,3600.000000,14541.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,4.00,0.8200,3600.000000,50699.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,3.00,0.8800,3600.000000,25510.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,3.00,0.8800,3600.000000,11344.000000,0
,mip1_eqcon2_presolve0,23.666667,3.35,0.7745,3541.186167,27123.516667,1

In [39]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 3.00 & 0.87 & 3600.00 & 3431.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 3.00 & 0.73 & 3600.00 & 3328.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 3039.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 3.00 & 0.77 & 3600.00 & 2321.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 2.00 & 0.85 & 3600.00 & 2795.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 2.00 & 0.95 & 3600.00 & 2292.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 4.00 & 0.83 & 3600.00 & 4627.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 3.00 & 0.91 & 3600.00 & 2875.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 2.00 & 0.94 & 3600.00 & 1777.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 2.00 & 0.92 & 3600.00 & 1756.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 2.00 & 0.97 & 3600.00 & 4578.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 2.00 & 0.96 & 3600.00 & 2438.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 2.00 & 0.97 & 3600.00 & 1645.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 2.00 & 0.97 & 3600.00 & 1913.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 2.00 & 0.96 & 3600.00 & 2310.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 5.00 & 0.62 & 3600.00 & 29574.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 3.00 & 0.67 & 3600.00 & 17550.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 6.00 & 0.57 & 3600.00 & 34470.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 3.00 & 0.80 & 3600.00 & 4707.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 4.00 & 0.50 & 3600.00 & 28904.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 3.00 & 0.86 & 3600.00 & 20031.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 3.00 & 0.85 & 3600.00 & 9862.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 5.00 & 0.75 & 3600.00 & 27086.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 2.00 & 0.93 & 3600.00 & 4180.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 4.00 & 0.79 & 3600.00 & 12028.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 2.00 & 0.95 & 3600.00 & 7369.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 3.00 & 0.91 & 3600.00 & 7659.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 3.00 & 0.92 & 3600.01 & 10202.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 2.00 & 0.96 & 3600.01 & 3818.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 3.00 & 0.92 & 3600.00 & 9129.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 4.00 & 0.56 & 3600.00 & 20247.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 4.00 & 0.43 & 3600.00 & 269144.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 31434.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 3.00 & 0.81 & 3600.00 & 20142.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 5.00 & 0.62 & 3600.00 & 55818.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 4.00 & 0.76 & 3600.00 & 33325.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 5.00 & 0.62 & 3600.00 & 52798.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 3.00 & 0.84 & 3600.00 & 9629.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 3.00 & 0.85 & 3600.00 & 13897.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 4.00 & 0.78 & 3600.00 & 12796.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 3.00 & 0.89 & 3600.00 & 11008.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 3.00 & 0.90 & 3600.00 & 20504.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 3.00 & 0.91 & 3600.00 & 14054.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 3.00 & 0.90 & 3600.00 & 13995.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 4.00 & 0.88 & 3600.00 & 11348.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 4.00 & 0.64 & 3600.00 & 120240.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 71.15 & 6055.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 5.00 & 0.50 & 3600.00 & 88128.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 4.00 & 0.60 & 3600.00 & 105884.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 4.00 & 0.33 & 3600.00 & 98609.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 3.00 & 0.83 & 3600.00 & 71082.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 5.00 & 0.58 & 3600.00 & 29550.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 4.00 & 0.78 & 3600.00 & 49912.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 4.00 & 0.69 & 3600.00 & 50430.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 4.00 & 0.73 & 3600.00 & 19758.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 3.00 & 0.88 & 3600.00 & 27836.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 3.00 & 0.86 & 3600.00 & 14541.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 4.00 & 0.82 & 3600.00 & 50699.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 3.00 & 0.88 & 3600.00 & 25510.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 3.00 & 0.88 & 3600.00 & 11344.00 & 0 \\
mip1\_eqcon2\_presolve0 & 3.35 & 0.77 & 3541.19 & 27123.52 & 1 \\
\bottomrule
\end{tabular}

In [40]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k2_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.000000,0.000,11.040000,81.0,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000,1.630000,3.0,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000,4.580000,3.0,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000,13.390000,7.0,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.000000,0.000,5.870000,9.0,1
5,random_n60_k2_pos30_neg5_err10_1.g,38.000000,38.000000,0.000,35.940000,468.0,1
6,random_n60_k2_pos30_neg5_err10_2.g,24.000000,24.000000,0.000,4.890000,15.0,1
7,random_n60_k2_pos30_neg5_err10_3.g,34.000000,34.000000,0.000,30.020000,70.0,1
8,random_n60_k2_pos30_neg5_err10_4.g,35.000000,35.000000,0.000,23.350000,134.0,1
9,random_n60_k2_pos30_neg5_err10_5.g,25.000000,25.000000,0.000,10.730000,66.0,1
10,random_n60_k2_pos30_neg5_err20_1.g,61.000000,44.000000,0.280,3600.000000,17707.0,0
11,random_n60_k2_pos30_neg5_err20_2.g,53.000000,53.000000,0.000,750.350000,4883.0,1
12,random_n60_k2_pos30_neg5_err20_3.g,63.000000,56.000000,0.110,3600.000000,15352.0,0
13,random_n60_k2_pos30_neg5_err20_4.g,67.000000,45.000000,0.330,3600.010000,13787.0,0
14,random_n60_k2_pos30_neg5_err20_5.g,54.000000,46.000000,0.150,3600.000000,12644.0,0
,edge1_k2_default,34.866667,31.266667,0.058,1019.453333,4348.6,11

In [41]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 11.04 & 81.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 1.63 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 4.58 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 13.39 & 7.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 5.87 & 9.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 38.00 & 0.00 & 35.94 & 468.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 4.89 & 15.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 30.02 & 70.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 23.35 & 134.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 10.73 & 66.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 44.00 & 0.28 & 3600.00 & 17707.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 53.00 & 0.00 & 750.35 & 4883.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 56.00 & 0.11 & 3600.00 & 15352.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 45.00 & 0.33 & 3600.01 & 13787.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 46.00 & 0.15 & 3600.00 & 12644.00 & 0 \\
edge1\_k2\_default & 31.27 & 0.06 & 1019.45 & 4348.60 & 11 \\
\bottomrule
\end{tabular}

In [42]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k3_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k3_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k3_pos30_neg5_err5_1.g,13.0,13.000000,0.000000,0.920000,7.000000,1
1,random_n60_k3_pos30_neg5_err5_2.g,9.0,9.000000,0.000000,2.540000,7.000000,1
2,random_n60_k3_pos30_neg5_err5_3.g,14.0,14.000000,0.000000,1.710000,19.000000,1
3,random_n60_k3_pos30_neg5_err5_4.g,15.0,15.000000,0.000000,4.270000,18.000000,1
4,random_n60_k3_pos30_neg5_err5_5.g,8.0,8.000000,0.000000,1.920000,5.000000,1
5,random_n60_k3_pos30_neg5_err10_1.g,21.0,21.000000,0.000000,4.700000,170.000000,1
6,random_n60_k3_pos30_neg5_err10_2.g,20.0,20.000000,0.000000,2.080000,55.000000,1
7,random_n60_k3_pos30_neg5_err10_3.g,20.0,20.000000,0.000000,7.150000,203.000000,1
8,random_n60_k3_pos30_neg5_err10_4.g,28.0,28.000000,0.000000,24.810000,416.000000,1
9,random_n60_k3_pos30_neg5_err10_5.g,19.0,19.000000,0.000000,3.120000,74.000000,1
10,random_n60_k3_pos30_neg5_err20_1.g,41.0,41.000000,0.000000,1984.420000,35689.000000,1
11,random_n60_k3_pos30_neg5_err20_2.g,35.0,35.000000,0.000000,404.750000,6015.000000,1
12,random_n60_k3_pos30_neg5_err20_3.g,37.0,37.000000,0.000000,1149.680000,25188.000000,1
13,random_n60_k3_pos30_neg5_err20_4.g,49.0,34.000000,0.310000,3600.000000,22806.000000,0
14,random_n60_k3_pos30_neg5_err20_5.g,37.0,30.000000,0.190000,3600.000000,51197.000000,0
,edge1_k3_default,24.4,22.933333,0.033333,719.471333,9457.933333,13

In [43]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 0.92 & 7.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 2.54 & 7.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 1.71 & 19.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 4.27 & 18.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 1.92 & 5.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 4.70 & 170.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 2.08 & 55.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 7.15 & 203.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 24.81 & 416.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 3.12 & 74.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 41.00 & 0.00 & 1984.42 & 35689.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 35.00 & 0.00 & 404.75 & 6015.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 37.00 & 0.00 & 1149.68 & 25188.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 34.00 & 0.31 & 3600.00 & 22806.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 30.00 & 0.19 & 3600.00 & 51197.00 & 0 \\
edge1\_k3\_default & 22.93 & 0.03 & 719.47 & 9457.93 & 13 \\
\bottomrule
\end{tabular}

In [44]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k4_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k4_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k4_pos30_neg5_err5_1.g,9.000000,9.000000,0.0,1.090000,32.0,1
1,random_n60_k4_pos30_neg5_err5_2.g,7.000000,7.000000,0.0,1.190000,7.0,1
2,random_n60_k4_pos30_neg5_err5_3.g,9.000000,9.000000,0.0,1.220000,7.0,1
3,random_n60_k4_pos30_neg5_err5_4.g,16.000000,16.000000,0.0,3.540000,136.0,1
4,random_n60_k4_pos30_neg5_err5_5.g,13.000000,13.000000,0.0,1.990000,36.0,1
5,random_n60_k4_pos30_neg5_err10_1.g,17.000000,17.000000,0.0,3.320000,159.0,1
6,random_n60_k4_pos30_neg5_err10_2.g,13.000000,13.000000,0.0,2.170000,27.0,1
7,random_n60_k4_pos30_neg5_err10_3.g,19.000000,19.000000,0.0,7.950000,253.0,1
8,random_n60_k4_pos30_neg5_err10_4.g,20.000000,20.000000,0.0,3.990000,123.0,1
9,random_n60_k4_pos30_neg5_err10_5.g,18.000000,18.000000,0.0,3.290000,108.0,1
10,random_n60_k4_pos30_neg5_err20_1.g,28.000000,28.000000,0.0,433.730000,11911.0,1
11,random_n60_k4_pos30_neg5_err20_2.g,29.000000,29.000000,0.0,490.370000,18293.0,1
12,random_n60_k4_pos30_neg5_err20_3.g,32.000000,32.000000,0.0,1110.890000,32811.0,1
13,random_n60_k4_pos30_neg5_err20_4.g,30.000000,30.000000,0.0,1244.750000,29040.0,1
14,random_n60_k4_pos30_neg5_err20_5.g,32.000000,32.000000,0.0,1106.170000,24807.0,1
,edge1_k4_default,19.466667,19.466667,0.0,294.377333,7850.0,15

In [45]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 1.09 & 32.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 1.19 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 1.22 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 3.54 & 136.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 1.99 & 36.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 3.32 & 159.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 2.17 & 27.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 7.95 & 253.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 3.99 & 123.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 3.29 & 108.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 28.00 & 0.00 & 433.73 & 11911.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 29.00 & 0.00 & 490.37 & 18293.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 32.00 & 0.00 & 1110.89 & 32811.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 30.00 & 0.00 & 1244.75 & 29040.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 32.00 & 0.00 & 1106.17 & 24807.00 & 1 \\
edge1\_k4\_default & 19.47 & 0.00 & 294.38 & 7850.00 & 15 \\
\bottomrule
\end{tabular}

In [46]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k5_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k5_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k5_pos30_neg5_err5_1.g,11.000000,11.000000,0.0,2.220,121.0,1
1,random_n60_k5_pos30_neg5_err5_2.g,4.000000,4.000000,0.0,1.130,7.0,1
2,random_n60_k5_pos30_neg5_err5_3.g,10.000000,10.000000,0.0,1.640,29.0,1
3,random_n60_k5_pos30_neg5_err5_4.g,10.000000,10.000000,0.0,1.450,21.0,1
4,random_n60_k5_pos30_neg5_err5_5.g,6.000000,6.000000,0.0,1.630,14.0,1
5,random_n60_k5_pos30_neg5_err10_1.g,18.000000,18.000000,0.0,25.760,1564.0,1
6,random_n60_k5_pos30_neg5_err10_2.g,12.000000,12.000000,0.0,2.150,77.0,1
7,random_n60_k5_pos30_neg5_err10_3.g,18.000000,18.000000,0.0,23.380,2331.0,1
8,random_n60_k5_pos30_neg5_err10_4.g,13.000000,13.000000,0.0,2.360,77.0,1
9,random_n60_k5_pos30_neg5_err10_5.g,15.000000,15.000000,0.0,4.080,175.0,1
10,random_n60_k5_pos30_neg5_err20_1.g,23.000000,23.000000,0.0,197.020,12337.0,1
11,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.000000,0.0,136.730,4677.0,1
12,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.000000,0.0,228.090,15647.0,1
13,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.000000,0.0,914.650,37768.0,1
14,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.000000,0.0,467.830,16214.0,1
,edge1_k5_default,15.733333,15.733333,0.0,134.008,6070.6,15

In [47]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 2.22 & 121.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 1.13 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 1.64 & 29.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 1.45 & 21.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 1.63 & 14.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 18.00 & 0.00 & 25.76 & 1564.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 2.15 & 77.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 18.00 & 0.00 & 23.38 & 2331.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 2.36 & 77.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 4.08 & 175.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 23.00 & 0.00 & 197.02 & 12337.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 22.00 & 0.00 & 136.73 & 4677.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 22.00 & 0.00 & 228.09 & 15647.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 26.00 & 0.00 & 914.65 & 37768.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 26.00 & 0.00 & 467.83 & 16214.00 & 1 \\
edge1\_k5\_default & 15.73 & 0.00 & 134.01 & 6070.60 & 15 \\
\bottomrule
\end{tabular}

In [48]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k2_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,3.000000,0.870,3600.0,4085.0,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,4.000000,0.640,3600.0,4220.0,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,3.000000,0.670,3600.0,3293.0,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,3.000000,0.770,3600.0,3422.0,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,3.000000,0.770,3600.0,4572.0,0
5,random_n60_k2_pos30_neg5_err10_1.g,38.000000,3.000000,0.920,3600.0,5171.0,0
6,random_n60_k2_pos30_neg5_err10_2.g,24.000000,4.000000,0.830,3600.0,6253.0,0
7,random_n60_k2_pos30_neg5_err10_3.g,34.000000,3.000000,0.910,3600.0,2779.0,0
8,random_n60_k2_pos30_neg5_err10_4.g,35.000000,3.000000,0.910,3600.0,3100.0,0
9,random_n60_k2_pos30_neg5_err10_5.g,25.000000,2.000000,0.920,3600.0,2634.0,0
10,random_n60_k2_pos30_neg5_err20_1.g,61.000000,2.000000,0.970,3600.0,3992.0,0
11,random_n60_k2_pos30_neg5_err20_2.g,53.000000,3.000000,0.940,3600.0,4991.0,0
12,random_n60_k2_pos30_neg5_err20_3.g,63.000000,3.000000,0.950,3600.0,2432.0,0
13,random_n60_k2_pos30_neg5_err20_4.g,67.000000,3.000000,0.960,3600.0,2793.0,0
14,random_n60_k2_pos30_neg5_err20_5.g,54.000000,2.000000,0.960,3600.0,2801.0,0
,edge1_k2_presolve0,34.866667,2.933333,0.866,3600.0,3769.2,0

In [49]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 3.00 & 0.87 & 3600.00 & 4085.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 4.00 & 0.64 & 3600.00 & 4220.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 3.00 & 0.67 & 3600.00 & 3293.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 3.00 & 0.77 & 3600.00 & 3422.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 3.00 & 0.77 & 3600.00 & 4572.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 3.00 & 0.92 & 3600.00 & 5171.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 4.00 & 0.83 & 3600.00 & 6253.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 3.00 & 0.91 & 3600.00 & 2779.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 3.00 & 0.91 & 3600.00 & 3100.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 2.00 & 0.92 & 3600.00 & 2634.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 2.00 & 0.97 & 3600.00 & 3992.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 3.00 & 0.94 & 3600.00 & 4991.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 3.00 & 0.95 & 3600.00 & 2432.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 3.00 & 0.96 & 3600.00 & 2793.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 2.00 & 0.96 & 3600.00 & 2801.00 & 0 \\
edge1\_k2\_presolve0 & 2.93 & 0.87 & 3600.00 & 3769.20 & 0 \\
\bottomrule
\end{tabular}

In [50]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k3_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k3_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k3_pos30_neg5_err5_1.g,13.0,3.000000,0.770000,3600.0,62459.000000,0
1,random_n60_k3_pos30_neg5_err5_2.g,9.0,5.000000,0.440000,3600.0,49405.000000,0
2,random_n60_k3_pos30_neg5_err5_3.g,14.0,4.000000,0.710000,3600.0,29428.000000,0
3,random_n60_k3_pos30_neg5_err5_4.g,15.0,3.000000,0.800000,3600.0,6745.000000,0
4,random_n60_k3_pos30_neg5_err5_5.g,8.0,6.000000,0.250000,3600.0,33217.000000,0
5,random_n60_k3_pos30_neg5_err10_1.g,21.0,3.000000,0.860000,3600.0,13013.000000,0
6,random_n60_k3_pos30_neg5_err10_2.g,20.0,3.000000,0.850000,3600.0,12979.000000,0
7,random_n60_k3_pos30_neg5_err10_3.g,20.0,4.000000,0.800000,3600.0,20841.000000,0
8,random_n60_k3_pos30_neg5_err10_4.g,28.0,3.000000,0.890000,3600.0,7799.000000,0
9,random_n60_k3_pos30_neg5_err10_5.g,19.0,4.000000,0.790000,3600.0,14779.000000,0
10,random_n60_k3_pos30_neg5_err20_1.g,41.0,4.000000,0.900000,3600.0,15254.000000,0
11,random_n60_k3_pos30_neg5_err20_2.g,35.0,2.000000,0.940000,3600.0,10164.000000,0
12,random_n60_k3_pos30_neg5_err20_3.g,37.0,3.000000,0.920000,3600.0,14034.000000,0
13,random_n60_k3_pos30_neg5_err20_4.g,49.0,2.000000,0.960000,3600.0,6844.000000,0
14,random_n60_k3_pos30_neg5_err20_5.g,37.0,3.000000,0.920000,3600.0,11023.000000,0
,edge1_k3_presolve0,24.4,3.466667,0.786667,3600.0,20532.266667,0

In [51]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 3.00 & 0.77 & 3600.00 & 62459.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 5.00 & 0.44 & 3600.00 & 49405.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 4.00 & 0.71 & 3600.00 & 29428.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 3.00 & 0.80 & 3600.00 & 6745.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 6.00 & 0.25 & 3600.00 & 33217.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 3.00 & 0.86 & 3600.00 & 13013.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 3.00 & 0.85 & 3600.00 & 12979.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 4.00 & 0.80 & 3600.00 & 20841.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 3.00 & 0.89 & 3600.00 & 7799.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 4.00 & 0.79 & 3600.00 & 14779.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 4.00 & 0.90 & 3600.00 & 15254.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 2.00 & 0.94 & 3600.00 & 10164.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 3.00 & 0.92 & 3600.00 & 14034.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 2.00 & 0.96 & 3600.00 & 6844.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 3.00 & 0.92 & 3600.00 & 11023.00 & 0 \\
edge1\_k3\_presolve0 & 3.47 & 0.79 & 3600.00 & 20532.27 & 0 \\
\bottomrule
\end{tabular}

In [52]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k4_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k4_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k4_pos30_neg5_err5_1.g,9.0,5.0,0.440000,3600.000000,32802.000000,0
1,random_n60_k4_pos30_neg5_err5_2.g,7.0,7.0,0.000000,3292.940000,130909.000000,1
2,random_n60_k4_pos30_neg5_err5_3.g,9.0,5.0,0.440000,3600.000000,33031.000000,0
3,random_n60_k4_pos30_neg5_err5_4.g,16.0,4.0,0.750000,3600.000000,36670.000000,0
4,random_n60_k4_pos30_neg5_err5_5.g,13.0,5.0,0.620000,3600.000000,88730.000000,0
5,random_n60_k4_pos30_neg5_err10_1.g,17.0,5.0,0.710000,3600.000000,47149.000000,0
6,random_n60_k4_pos30_neg5_err10_2.g,13.0,6.0,0.540000,3600.000000,94777.000000,0
7,random_n60_k4_pos30_neg5_err10_3.g,19.0,3.0,0.840000,3600.000000,16408.000000,0
8,random_n60_k4_pos30_neg5_err10_4.g,20.0,4.0,0.800000,3600.000000,18171.000000,0
9,random_n60_k4_pos30_neg5_err10_5.g,18.0,5.0,0.720000,3600.000000,20194.000000,0
10,random_n60_k4_pos30_neg5_err20_1.g,28.0,3.0,0.890000,3600.000000,18394.000000,0
11,random_n60_k4_pos30_neg5_err20_2.g,29.0,3.0,0.900000,3600.000000,17061.000000,0
12,random_n60_k4_pos30_neg5_err20_3.g,33.0,3.0,0.910000,3600.000000,16874.000000,0
13,random_n60_k4_pos30_neg5_err20_4.g,31.0,3.0,0.900000,3600.000000,16286.000000,0
14,random_n60_k4_pos30_neg5_err20_5.g,32.0,5.0,0.840000,3600.000000,19040.000000,0
,edge1_k4_presolve0,19.6,4.4,0.686667,3579.529333,40433.066667,1

In [53]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 5.00 & 0.44 & 3600.00 & 32802.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 3292.94 & 130909.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 5.00 & 0.44 & 3600.00 & 33031.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 4.00 & 0.75 & 3600.00 & 36670.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 5.00 & 0.62 & 3600.00 & 88730.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 5.00 & 0.71 & 3600.00 & 47149.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 6.00 & 0.54 & 3600.00 & 94777.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 3.00 & 0.84 & 3600.00 & 16408.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 4.00 & 0.80 & 3600.00 & 18171.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 5.00 & 0.72 & 3600.00 & 20194.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 3.00 & 0.89 & 3600.00 & 18394.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 3.00 & 0.90 & 3600.00 & 17061.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 3.00 & 0.91 & 3600.00 & 16874.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 3.00 & 0.90 & 3600.00 & 16286.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 5.00 & 0.84 & 3600.00 & 19040.00 & 0 \\
edge1\_k4\_presolve0 & 4.40 & 0.69 & 3579.53 & 40433.07 & 1 \\
\bottomrule
\end{tabular}

In [54]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k5_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k5_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k5_pos30_neg5_err5_1.g,11.000000,6.000000,0.450,3600.000000,173485.000000,0
1,random_n60_k5_pos30_neg5_err5_2.g,4.000000,4.000000,0.000,93.280000,11213.000000,1
2,random_n60_k5_pos30_neg5_err5_3.g,10.000000,5.000000,0.500,3600.000000,73544.000000,0
3,random_n60_k5_pos30_neg5_err5_4.g,10.000000,5.000000,0.500,3600.000000,79858.000000,0
4,random_n60_k5_pos30_neg5_err5_5.g,6.000000,6.000000,0.000,1723.120000,45769.000000,1
5,random_n60_k5_pos30_neg5_err10_1.g,18.000000,4.000000,0.780,3600.000000,111012.000000,0
6,random_n60_k5_pos30_neg5_err10_2.g,12.000000,6.000000,0.500,3600.000000,37859.000000,0
7,random_n60_k5_pos30_neg5_err10_3.g,18.000000,4.000000,0.780,3600.000000,35852.000000,0
8,random_n60_k5_pos30_neg5_err10_4.g,13.000000,5.000000,0.620,3600.000000,72322.000000,0
9,random_n60_k5_pos30_neg5_err10_5.g,15.000000,5.000000,0.670,3600.000000,48854.000000,0
10,random_n60_k5_pos30_neg5_err20_1.g,23.000000,4.000000,0.830,3600.000000,58589.000000,0
11,random_n60_k5_pos30_neg5_err20_2.g,22.000000,4.000000,0.820,3600.000000,26375.000000,0
12,random_n60_k5_pos30_neg5_err20_3.g,22.000000,4.000000,0.820,3600.000000,31778.000000,0
13,random_n60_k5_pos30_neg5_err20_4.g,26.000000,4.000000,0.850,3600.000000,41100.000000,0
14,random_n60_k5_pos30_neg5_err20_5.g,26.000000,4.000000,0.850,3600.000000,16679.000000,0
,edge1_k5_presolve0,15.733333,4.666667,0.598,3241.093333,57619.266667,2

In [55]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 6.00 & 0.45 & 3600.00 & 173485.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 93.28 & 11213.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 5.00 & 0.50 & 3600.00 & 73544.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 5.00 & 0.50 & 3600.00 & 79858.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 1723.12 & 45769.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 4.00 & 0.78 & 3600.00 & 111012.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 6.00 & 0.50 & 3600.00 & 37859.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 4.00 & 0.78 & 3600.00 & 35852.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 5.00 & 0.62 & 3600.00 & 72322.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 5.00 & 0.67 & 3600.00 & 48854.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 4.00 & 0.83 & 3600.00 & 58589.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 4.00 & 0.82 & 3600.00 & 26375.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 4.00 & 0.82 & 3600.00 & 31778.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 4.00 & 0.85 & 3600.00 & 41100.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 4.00 & 0.85 & 3600.00 & 16679.00 & 0 \\
edge1\_k5\_presolve0 & 4.67 & 0.60 & 3241.09 & 57619.27 & 2 \\
\bottomrule
\end{tabular}

In [56]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k2_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k2_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.0,0.000,22.600000,76.0,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.0,0.000,12.080000,3.0,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.0,0.000,3.910000,3.0,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.0,0.000,17.050000,3.0,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.0,0.000,17.110000,9.0,1
5,random_n60_k2_pos30_neg5_err10_1.g,38.000000,38.0,0.000,191.490000,763.0,1
6,random_n60_k2_pos30_neg5_err10_2.g,24.000000,24.0,0.000,48.950000,64.0,1
7,random_n60_k2_pos30_neg5_err10_3.g,34.000000,34.0,0.000,53.320000,72.0,1
8,random_n60_k2_pos30_neg5_err10_4.g,35.000000,35.0,0.000,52.360000,92.0,1
9,random_n60_k2_pos30_neg5_err10_5.g,25.000000,25.0,0.000,20.520000,17.0,1
10,random_n60_k2_pos30_neg5_err20_1.g,61.000000,43.0,0.300,3600.000000,8866.0,0
11,random_n60_k2_pos30_neg5_err20_2.g,53.000000,53.0,0.000,3209.030000,8719.0,1
12,random_n60_k2_pos30_neg5_err20_3.g,63.000000,63.0,0.000,3115.870000,6042.0,1
13,random_n60_k2_pos30_neg5_err20_4.g,67.000000,42.0,0.370,3600.000000,7503.0,0
14,random_n60_k2_pos30_neg5_err20_5.g,54.000000,48.0,0.110,3600.000000,9855.0,0
,edge1_k2_eqcon2_default,34.866667,31.6,0.052,1170.952667,2805.8,12

In [57]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 23.00 & 0.00 & 22.60 & 76.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 11.00 & 0.00 & 12.08 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 3.91 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 13.00 & 0.00 & 17.05 & 3.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 17.11 & 9.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 38.00 & 0.00 & 191.49 & 763.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 24.00 & 0.00 & 48.95 & 64.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 34.00 & 0.00 & 53.32 & 72.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 35.00 & 0.00 & 52.36 & 92.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 25.00 & 0.00 & 20.52 & 17.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 43.00 & 0.30 & 3600.00 & 8866.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 53.00 & 0.00 & 3209.03 & 8719.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 63.00 & 0.00 & 3115.87 & 6042.00 & 1 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 42.00 & 0.37 & 3600.00 & 7503.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 48.00 & 0.11 & 3600.00 & 9855.00 & 0 \\
edge1\_k2\_eqcon2\_default & 31.60 & 0.05 & 1170.95 & 2805.80 & 12 \\
\bottomrule
\end{tabular}

In [58]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k3_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k3_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k3_pos30_neg5_err5_1.g,13.0,13.000000,0.000000,2.590000,9.0,1
1,random_n60_k3_pos30_neg5_err5_2.g,9.0,9.000000,0.000000,2.850000,11.0,1
2,random_n60_k3_pos30_neg5_err5_3.g,14.0,14.000000,0.000000,5.530000,63.0,1
3,random_n60_k3_pos30_neg5_err5_4.g,15.0,15.000000,0.000000,18.200000,31.0,1
4,random_n60_k3_pos30_neg5_err5_5.g,8.0,8.000000,0.000000,0.930000,5.0,1
5,random_n60_k3_pos30_neg5_err10_1.g,21.0,21.000000,0.000000,6.050000,94.0,1
6,random_n60_k3_pos30_neg5_err10_2.g,20.0,20.000000,0.000000,6.900000,50.0,1
7,random_n60_k3_pos30_neg5_err10_3.g,20.0,20.000000,0.000000,7.620000,191.0,1
8,random_n60_k3_pos30_neg5_err10_4.g,28.0,28.000000,0.000000,143.570000,1013.0,1
9,random_n60_k3_pos30_neg5_err10_5.g,19.0,19.000000,0.000000,5.520000,84.0,1
10,random_n60_k3_pos30_neg5_err20_1.g,41.0,41.000000,0.000000,1955.700000,16554.0,1
11,random_n60_k3_pos30_neg5_err20_2.g,35.0,35.000000,0.000000,1409.680000,14703.0,1
12,random_n60_k3_pos30_neg5_err20_3.g,37.0,37.000000,0.000000,1680.750000,18115.0,1
13,random_n60_k3_pos30_neg5_err20_4.g,49.0,35.000000,0.290000,3600.000000,12791.0,0
14,random_n60_k3_pos30_neg5_err20_5.g,37.0,37.000000,0.000000,1524.100000,15231.0,1
,edge1_k3_eqcon2_default,24.4,23.466667,0.019333,691.332667,5263.0,14

In [59]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 13.00 & 0.00 & 2.59 & 9.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 9.00 & 0.00 & 2.85 & 11.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 14.00 & 0.00 & 5.53 & 63.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 15.00 & 0.00 & 18.20 & 31.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 8.00 & 0.00 & 0.93 & 5.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 21.00 & 0.00 & 6.05 & 94.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 20.00 & 0.00 & 6.90 & 50.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 20.00 & 0.00 & 7.62 & 191.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 28.00 & 0.00 & 143.57 & 1013.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 19.00 & 0.00 & 5.52 & 84.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 41.00 & 0.00 & 1955.70 & 16554.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 35.00 & 0.00 & 1409.68 & 14703.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 37.00 & 0.00 & 1680.75 & 18115.00 & 1 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 35.00 & 0.29 & 3600.00 & 12791.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 37.00 & 0.00 & 1524.10 & 15231.00 & 1 \\
edge1\_k3\_eqcon2\_default & 23.47 & 0.02 & 691.33 & 5263.00 & 14 \\
\bottomrule
\end{tabular}

In [60]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k4_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k4_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k4_pos30_neg5_err5_1.g,9.000000,9.000000,0.0,1.670000,27.000000,1
1,random_n60_k4_pos30_neg5_err5_2.g,7.000000,7.000000,0.0,3.220000,7.000000,1
2,random_n60_k4_pos30_neg5_err5_3.g,9.000000,9.000000,0.0,4.450000,7.000000,1
3,random_n60_k4_pos30_neg5_err5_4.g,16.000000,16.000000,0.0,6.160000,172.000000,1
4,random_n60_k4_pos30_neg5_err5_5.g,13.000000,13.000000,0.0,2.790000,58.000000,1
5,random_n60_k4_pos30_neg5_err10_1.g,17.000000,17.000000,0.0,4.460000,70.000000,1
6,random_n60_k4_pos30_neg5_err10_2.g,13.000000,13.000000,0.0,2.200000,31.000000,1
7,random_n60_k4_pos30_neg5_err10_3.g,19.000000,19.000000,0.0,12.970000,194.000000,1
8,random_n60_k4_pos30_neg5_err10_4.g,20.000000,20.000000,0.0,6.800000,118.000000,1
9,random_n60_k4_pos30_neg5_err10_5.g,18.000000,18.000000,0.0,9.770000,99.000000,1
10,random_n60_k4_pos30_neg5_err20_1.g,28.000000,28.000000,0.0,506.020000,8846.000000,1
11,random_n60_k4_pos30_neg5_err20_2.g,29.000000,29.000000,0.0,379.600000,5194.000000,1
12,random_n60_k4_pos30_neg5_err20_3.g,32.000000,32.000000,0.0,605.240000,15411.000000,1
13,random_n60_k4_pos30_neg5_err20_4.g,30.000000,30.000000,0.0,871.410000,13438.000000,1
14,random_n60_k4_pos30_neg5_err20_5.g,32.000000,32.000000,0.0,1254.020000,18226.000000,1
,edge1_k4_eqcon2_default,19.466667,19.466667,0.0,244.718667,4126.533333,15

In [61]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 9.00 & 0.00 & 1.67 & 27.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 7.00 & 0.00 & 3.22 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 9.00 & 0.00 & 4.45 & 7.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 16.00 & 0.00 & 6.16 & 172.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 13.00 & 0.00 & 2.79 & 58.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 17.00 & 0.00 & 4.46 & 70.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 13.00 & 0.00 & 2.20 & 31.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 19.00 & 0.00 & 12.97 & 194.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 20.00 & 0.00 & 6.80 & 118.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 18.00 & 0.00 & 9.77 & 99.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 28.00 & 0.00 & 506.02 & 8846.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 29.00 & 0.00 & 379.60 & 5194.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 32.00 & 0.00 & 605.24 & 15411.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 30.00 & 0.00 & 871.41 & 13438.00 & 1 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 32.00 & 0.00 & 1254.02 & 18226.00 & 1 \\
edge1\_k4\_eqcon2\_default & 19.47 & 0.00 & 244.72 & 4126.53 & 15 \\
\bottomrule
\end{tabular}

In [62]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k5_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k5_eqcon2_default",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k5_pos30_neg5_err5_1.g,11.000000,11.000000,0.0,1.840,54.0,1
1,random_n60_k5_pos30_neg5_err5_2.g,4.000000,4.000000,0.0,1.190,7.0,1
2,random_n60_k5_pos30_neg5_err5_3.g,10.000000,10.000000,0.0,2.790,27.0,1
3,random_n60_k5_pos30_neg5_err5_4.g,10.000000,10.000000,0.0,1.410,20.0,1
4,random_n60_k5_pos30_neg5_err5_5.g,6.000000,6.000000,0.0,3.190,12.0,1
5,random_n60_k5_pos30_neg5_err10_1.g,18.000000,18.000000,0.0,20.160,973.0,1
6,random_n60_k5_pos30_neg5_err10_2.g,12.000000,12.000000,0.0,1.660,74.0,1
7,random_n60_k5_pos30_neg5_err10_3.g,18.000000,18.000000,0.0,45.260,2314.0,1
8,random_n60_k5_pos30_neg5_err10_4.g,13.000000,13.000000,0.0,3.870,113.0,1
9,random_n60_k5_pos30_neg5_err10_5.g,15.000000,15.000000,0.0,7.090,91.0,1
10,random_n60_k5_pos30_neg5_err20_1.g,23.000000,23.000000,0.0,520.200,18467.0,1
11,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.000000,0.0,157.310,4540.0,1
12,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.000000,0.0,141.470,7924.0,1
13,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.000000,0.0,450.980,16425.0,1
14,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.000000,0.0,271.600,3721.0,1
,edge1_k5_eqcon2_default,15.733333,15.733333,0.0,108.668,3650.8,15

In [63]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 11.00 & 0.00 & 1.84 & 54.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 1.19 & 7.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 10.00 & 0.00 & 2.79 & 27.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 10.00 & 0.00 & 1.41 & 20.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 6.00 & 0.00 & 3.19 & 12.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 18.00 & 0.00 & 20.16 & 973.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 12.00 & 0.00 & 1.66 & 74.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 18.00 & 0.00 & 45.26 & 2314.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 13.00 & 0.00 & 3.87 & 113.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 15.00 & 0.00 & 7.09 & 91.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 23.00 & 0.00 & 520.20 & 18467.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 22.00 & 0.00 & 157.31 & 4540.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 22.00 & 0.00 & 141.47 & 7924.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 26.00 & 0.00 & 450.98 & 16425.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 26.00 & 0.00 & 271.60 & 3721.00 & 1 \\
edge1\_k5\_eqcon2\_default & 15.73 & 0.00 & 108.67 & 3650.80 & 15 \\
\bottomrule
\end{tabular}

In [64]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k2_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k2_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,3.000000,0.870000,3600.0,3431.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,3.000000,0.730000,3600.0,3328.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,4.000000,0.560000,3600.0,3039.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,3.000000,0.770000,3600.0,2321.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,2.000000,0.850000,3600.0,2795.000000,0
5,random_n60_k2_pos30_neg5_err10_1.g,38.000000,2.000000,0.950000,3600.0,2292.000000,0
6,random_n60_k2_pos30_neg5_err10_2.g,24.000000,4.000000,0.830000,3600.0,4627.000000,0
7,random_n60_k2_pos30_neg5_err10_3.g,34.000000,3.000000,0.910000,3600.0,2875.000000,0
8,random_n60_k2_pos30_neg5_err10_4.g,35.000000,2.000000,0.940000,3600.0,1777.000000,0
9,random_n60_k2_pos30_neg5_err10_5.g,25.000000,2.000000,0.920000,3600.0,1756.000000,0
10,random_n60_k2_pos30_neg5_err20_1.g,61.000000,2.000000,0.970000,3600.0,4578.000000,0
11,random_n60_k2_pos30_neg5_err20_2.g,53.000000,2.000000,0.960000,3600.0,2438.000000,0
12,random_n60_k2_pos30_neg5_err20_3.g,63.000000,2.000000,0.970000,3600.0,1645.000000,0
13,random_n60_k2_pos30_neg5_err20_4.g,67.000000,2.000000,0.970000,3600.0,1913.000000,0
14,random_n60_k2_pos30_neg5_err20_5.g,54.000000,2.000000,0.960000,3600.0,2310.000000,0
,edge1_k2_eqcon2_presolve0,34.866667,2.533333,0.877333,3600.0,2741.666667,0

In [65]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k2\_pos30\_neg5\_err5\_1.g & 3.00 & 0.87 & 3600.00 & 3431.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_2.g & 3.00 & 0.73 & 3600.00 & 3328.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 3039.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_4.g & 3.00 & 0.77 & 3600.00 & 2321.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err5\_5.g & 2.00 & 0.85 & 3600.00 & 2795.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_1.g & 2.00 & 0.95 & 3600.00 & 2292.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_2.g & 4.00 & 0.83 & 3600.00 & 4627.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_3.g & 3.00 & 0.91 & 3600.00 & 2875.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_4.g & 2.00 & 0.94 & 3600.00 & 1777.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err10\_5.g & 2.00 & 0.92 & 3600.00 & 1756.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_1.g & 2.00 & 0.97 & 3600.00 & 4578.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_2.g & 2.00 & 0.96 & 3600.00 & 2438.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_3.g & 2.00 & 0.97 & 3600.00 & 1645.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_4.g & 2.00 & 0.97 & 3600.00 & 1913.00 & 0 \\
random\_n60\_k2\_pos30\_neg5\_err20\_5.g & 2.00 & 0.96 & 3600.00 & 2310.00 & 0 \\
edge1\_k2\_eqcon2\_presolve0 & 2.53 & 0.88 & 3600.00 & 2741.67 & 0 \\
\bottomrule
\end{tabular}

In [66]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k3_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k3_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k3_pos30_neg5_err5_1.g,13.000000,5.0,0.62,3600.000000,29574.0,0
1,random_n60_k3_pos30_neg5_err5_2.g,9.000000,3.0,0.67,3600.000000,17550.0,0
2,random_n60_k3_pos30_neg5_err5_3.g,14.000000,6.0,0.57,3600.000000,34470.0,0
3,random_n60_k3_pos30_neg5_err5_4.g,15.000000,3.0,0.80,3600.000000,4707.0,0
4,random_n60_k3_pos30_neg5_err5_5.g,8.000000,4.0,0.50,3600.000000,28904.0,0
5,random_n60_k3_pos30_neg5_err10_1.g,21.000000,3.0,0.86,3600.000000,20031.0,0
6,random_n60_k3_pos30_neg5_err10_2.g,20.000000,3.0,0.85,3600.000000,9862.0,0
7,random_n60_k3_pos30_neg5_err10_3.g,20.000000,5.0,0.75,3600.000000,27086.0,0
8,random_n60_k3_pos30_neg5_err10_4.g,28.000000,2.0,0.93,3600.000000,4180.0,0
9,random_n60_k3_pos30_neg5_err10_5.g,19.000000,4.0,0.79,3600.000000,12028.0,0
10,random_n60_k3_pos30_neg5_err20_1.g,41.000000,2.0,0.95,3600.000000,7369.0,0
11,random_n60_k3_pos30_neg5_err20_2.g,35.000000,3.0,0.91,3600.000000,7659.0,0
12,random_n60_k3_pos30_neg5_err20_3.g,37.000000,3.0,0.92,3600.010000,10202.0,0
13,random_n60_k3_pos30_neg5_err20_4.g,49.000000,2.0,0.96,3600.010000,3818.0,0
14,random_n60_k3_pos30_neg5_err20_5.g,39.000000,3.0,0.92,3600.000000,9129.0,0
,edge1_k3_eqcon2_presolve0,24.533333,3.4,0.80,3600.001333,15104.6,0

In [67]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k3\_pos30\_neg5\_err5\_1.g & 5.00 & 0.62 & 3600.00 & 29574.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_2.g & 3.00 & 0.67 & 3600.00 & 17550.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_3.g & 6.00 & 0.57 & 3600.00 & 34470.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_4.g & 3.00 & 0.80 & 3600.00 & 4707.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err5\_5.g & 4.00 & 0.50 & 3600.00 & 28904.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_1.g & 3.00 & 0.86 & 3600.00 & 20031.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_2.g & 3.00 & 0.85 & 3600.00 & 9862.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_3.g & 5.00 & 0.75 & 3600.00 & 27086.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_4.g & 2.00 & 0.93 & 3600.00 & 4180.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err10\_5.g & 4.00 & 0.79 & 3600.00 & 12028.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_1.g & 2.00 & 0.95 & 3600.00 & 7369.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_2.g & 3.00 & 0.91 & 3600.00 & 7659.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_3.g & 3.00 & 0.92 & 3600.01 & 10202.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_4.g & 2.00 & 0.96 & 3600.01 & 3818.00 & 0 \\
random\_n60\_k3\_pos30\_neg5\_err20\_5.g & 3.00 & 0.92 & 3600.00 & 9129.00 & 0 \\
edge1\_k3\_eqcon2\_presolve0 & 3.40 & 0.80 & 3600.00 & 15104.60 & 0 \\
\bottomrule
\end{tabular}

In [68]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k4_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k4_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k4_pos30_neg5_err5_1.g,9.000000,4.000000,0.560,3600.0,20247.0,0
1,random_n60_k4_pos30_neg5_err5_2.g,7.000000,4.000000,0.430,3600.0,269144.0,0
2,random_n60_k4_pos30_neg5_err5_3.g,9.000000,4.000000,0.560,3600.0,31434.0,0
3,random_n60_k4_pos30_neg5_err5_4.g,16.000000,3.000000,0.810,3600.0,20142.0,0
4,random_n60_k4_pos30_neg5_err5_5.g,13.000000,5.000000,0.620,3600.0,55818.0,0
5,random_n60_k4_pos30_neg5_err10_1.g,17.000000,4.000000,0.760,3600.0,33325.0,0
6,random_n60_k4_pos30_neg5_err10_2.g,13.000000,5.000000,0.620,3600.0,52798.0,0
7,random_n60_k4_pos30_neg5_err10_3.g,19.000000,3.000000,0.840,3600.0,9629.0,0
8,random_n60_k4_pos30_neg5_err10_4.g,20.000000,3.000000,0.850,3600.0,13897.0,0
9,random_n60_k4_pos30_neg5_err10_5.g,18.000000,4.000000,0.780,3600.0,12796.0,0
10,random_n60_k4_pos30_neg5_err20_1.g,28.000000,3.000000,0.890,3600.0,11008.0,0
11,random_n60_k4_pos30_neg5_err20_2.g,29.000000,3.000000,0.900,3600.0,20504.0,0
12,random_n60_k4_pos30_neg5_err20_3.g,32.000000,3.000000,0.910,3600.0,14054.0,0
13,random_n60_k4_pos30_neg5_err20_4.g,30.000000,3.000000,0.900,3600.0,13995.0,0
14,random_n60_k4_pos30_neg5_err20_5.g,32.000000,4.000000,0.880,3600.0,11348.0,0
,edge1_k4_eqcon2_presolve0,19.466667,3.666667,0.754,3600.0,39342.6,0

In [69]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k4\_pos30\_neg5\_err5\_1.g & 4.00 & 0.56 & 3600.00 & 20247.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_2.g & 4.00 & 0.43 & 3600.00 & 269144.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_3.g & 4.00 & 0.56 & 3600.00 & 31434.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_4.g & 3.00 & 0.81 & 3600.00 & 20142.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err5\_5.g & 5.00 & 0.62 & 3600.00 & 55818.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_1.g & 4.00 & 0.76 & 3600.00 & 33325.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_2.g & 5.00 & 0.62 & 3600.00 & 52798.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_3.g & 3.00 & 0.84 & 3600.00 & 9629.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_4.g & 3.00 & 0.85 & 3600.00 & 13897.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err10\_5.g & 4.00 & 0.78 & 3600.00 & 12796.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_1.g & 3.00 & 0.89 & 3600.00 & 11008.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_2.g & 3.00 & 0.90 & 3600.00 & 20504.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_3.g & 3.00 & 0.91 & 3600.00 & 14054.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_4.g & 3.00 & 0.90 & 3600.00 & 13995.00 & 0 \\
random\_n60\_k4\_pos30\_neg5\_err20\_5.g & 4.00 & 0.88 & 3600.00 & 11348.00 & 0 \\
edge1\_k4\_eqcon2\_presolve0 & 3.67 & 0.75 & 3600.00 & 39342.60 & 0 \\
\bottomrule
\end{tabular}

In [70]:
form_ = "edge1"
method_ = "mip"

file=f"edge1/{method_}_n{n_}_k5_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"edge1_k5_eqcon2_presolve0",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k5_pos30_neg5_err5_1.g,11.0,4.0,0.640000,3600.000000,120240.0,0
1,random_n60_k5_pos30_neg5_err5_2.g,4.0,4.0,0.000000,71.150000,6055.0,1
2,random_n60_k5_pos30_neg5_err5_3.g,10.0,5.0,0.500000,3600.000000,88128.0,0
3,random_n60_k5_pos30_neg5_err5_4.g,10.0,4.0,0.600000,3600.000000,105884.0,0
4,random_n60_k5_pos30_neg5_err5_5.g,6.0,4.0,0.330000,3600.000000,98609.0,0
5,random_n60_k5_pos30_neg5_err10_1.g,18.0,3.0,0.830000,3600.000000,71082.0,0
6,random_n60_k5_pos30_neg5_err10_2.g,12.0,5.0,0.580000,3600.000000,29550.0,0
7,random_n60_k5_pos30_neg5_err10_3.g,18.0,4.0,0.780000,3600.000000,49912.0,0
8,random_n60_k5_pos30_neg5_err10_4.g,13.0,4.0,0.690000,3600.000000,50430.0,0
9,random_n60_k5_pos30_neg5_err10_5.g,15.0,4.0,0.730000,3600.000000,19758.0,0
10,random_n60_k5_pos30_neg5_err20_1.g,24.0,3.0,0.880000,3600.000000,27836.0,0
11,random_n60_k5_pos30_neg5_err20_2.g,22.0,3.0,0.860000,3600.000000,14541.0,0
12,random_n60_k5_pos30_neg5_err20_3.g,22.0,4.0,0.820000,3600.000000,50699.0,0
13,random_n60_k5_pos30_neg5_err20_4.g,26.0,3.0,0.880000,3600.000000,25510.0,0
14,random_n60_k5_pos30_neg5_err20_5.g,26.0,3.0,0.880000,3600.000000,11344.0,0
,edge1_k5_eqcon2_presolve0,15.8,3.8,0.666667,3364.743333,51305.2,1

In [71]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrr}
\toprule
instance & bs & gap & time & nodes & opt \\
\midrule
random\_n60\_k5\_pos30\_neg5\_err5\_1.g & 4.00 & 0.64 & 3600.00 & 120240.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_2.g & 4.00 & 0.00 & 71.15 & 6055.00 & 1 \\
random\_n60\_k5\_pos30\_neg5\_err5\_3.g & 5.00 & 0.50 & 3600.00 & 88128.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_4.g & 4.00 & 0.60 & 3600.00 & 105884.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err5\_5.g & 4.00 & 0.33 & 3600.00 & 98609.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_1.g & 3.00 & 0.83 & 3600.00 & 71082.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_2.g & 5.00 & 0.58 & 3600.00 & 29550.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_3.g & 4.00 & 0.78 & 3600.00 & 49912.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_4.g & 4.00 & 0.69 & 3600.00 & 50430.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err10\_5.g & 4.00 & 0.73 & 3600.00 & 19758.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_1.g & 3.00 & 0.88 & 3600.00 & 27836.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_2.g & 3.00 & 0.86 & 3600.00 & 14541.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_3.g & 4.00 & 0.82 & 3600.00 & 50699.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_4.g & 3.00 & 0.88 & 3600.00 & 25510.00 & 0 \\
random\_n60\_k5\_pos30\_neg5\_err20\_5.g & 3.00 & 0.88 & 3600.00 & 11344.00 & 0 \\
edge1\_k5\_eqcon2\_presolve0 & 3.80 & 0.67 & 3364.74 & 51305.20 & 1 \\
\bottomrule
\end{tabular}