In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pdfkit as pdf

In [2]:
prob_ = "signed_graphs"
n_ = 60

In [3]:
form_ = "edge1"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp1_n60 = pd.DataFrame()
lp1_n60 = pd.concat([lp1_n60, df], ignore_index=True)
lp1_n60.columns = ['instance','bs','time']
#lp1_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bs':lp1_n60['bs'].mean(),
    'time':lp1_n60['time'].mean()
    },index=[""]
)

lp1_n60 = pd.concat([lp1_n60,tab])
lp1_n60['instance'] = lp1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp1_n60

                              instance   bs   time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  0.060
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  0.050
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  0.060
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  0.060
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  0.050
..                                 ...  ...    ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.030
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.030
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.030
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.030
                                resume  0.0  0.039

[61 rows x 3 columns]

In [4]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.00,0.000000,11.0400,81.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.00,0.000000,1.6300,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.00,0.000000,4.5800,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.00,0.000000,13.3900,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.00,0.000000,5.8700,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.00,0.000000,136.7300,4677.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.00,0.000000,228.0900,15647.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.00,0.000000,914.6500,37768.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.00,0.000000,467.8300,16214.000000,1
,resume,23.616667,22.35,0.022833,541.8275,6931.783333,54

In [5]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60_p0 = pd.DataFrame()
mip1_n60_p0 = pd.concat([mip1_n60_p0, df], ignore_index=True)
mip1_n60_p0.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip1_n60_p0['bb'].mean(),
    'bs':mip1_n60_p0['bs'].mean(),
    'gap':mip1_n60_p0['gap'].mean(),
    'time':mip1_n60_p0['time'].mean(),
    'nodes':mip1_n60_p0['nodes'].mean(),
    'opt':mip1_n60_p0['opt'].sum()
    },index=[""]
)

mip1_n60_p0 = pd.concat([mip1_n60_p0,tab])
mip1_n60_p0['instance'] = mip1_n60_p0['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60_p0

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,3.000000,0.870000,3600.000000,4085.00,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,4.000000,0.640000,3600.000000,4220.00,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,3.000000,0.670000,3600.000000,3293.00,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,3.000000,0.770000,3600.000000,3422.00,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,3.000000,0.770000,3600.000000,4572.00,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,4.000000,0.820000,3600.000000,26375.00,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,4.000000,0.820000,3600.000000,31778.00,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,4.000000,0.850000,3600.000000,41100.00,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,4.000000,0.850000,3600.000000,16679.00,0
,resume,23.65,3.866667,0.734333,3505.155667,30588.45,3

In [6]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60 = pd.DataFrame()
mip1_n60 = pd.concat([mip1_n60, df], ignore_index=True)
mip1_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip1_n60['bb'].mean(),
    'bs':mip1_n60['bs'].mean(),
    'gap':mip1_n60['gap'].mean(),
    'time':mip1_n60['time'].mean(),
    'nodes':mip1_n60['nodes'].mean(),
    'opt':mip1_n60['opt'].sum()
    },index=[""]
)

mip1_n60 = pd.concat([mip1_n60,tab])
mip1_n60['instance'] = mip1_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,23.000000,0.000000,22.600,76.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,12.080,3.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,3.910,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,17.050,3.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,13.000000,0.000000,17.110,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,22.000000,0.000000,157.310,4540.000000,1
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,22.000000,0.000000,141.470,7924.000000,1
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,26.000000,0.000000,450.980,16425.000000,1
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,26.000000,0.000000,271.600,3721.000000,1
,resume,23.616667,22.566667,0.017833,553.918,3961.533333,56

In [7]:
form_ = "edge1"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_eqcon2_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip1_n60_p0 = pd.DataFrame()
mip1_n60_p0 = pd.concat([mip1_n60_p0, df], ignore_index=True)
mip1_n60_p0.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip1_n60_p0['bb'].mean(),
    'bs':mip1_n60_p0['bs'].mean(),
    'gap':mip1_n60_p0['gap'].mean(),
    'time':mip1_n60_p0['time'].mean(),
    'nodes':mip1_n60_p0['nodes'].mean(),
    'opt':mip1_n60_p0['opt'].sum()
    },index=[""]
)

mip1_n60_p0 = pd.concat([mip1_n60_p0,tab])
mip1_n60_p0['instance'] = mip1_n60_p0['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip1_n60_p0

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,3.00,0.8700,3600.000000,3431.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,3.00,0.7300,3600.000000,3328.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,4.00,0.5600,3600.000000,3039.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,3.00,0.7700,3600.000000,2321.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,2.00,0.8500,3600.000000,2795.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.000000,3.00,0.8600,3600.000000,14541.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,4.00,0.8200,3600.000000,50699.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,3.00,0.8800,3600.000000,25510.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,3.00,0.8800,3600.000000,11344.000000,0
,resume,23.666667,3.35,0.7745,3541.186167,27123.516667,1

In [9]:
form_ = "edge2"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp2_n60 = pd.DataFrame()
lp2_n60 = pd.concat([lp2_n60, df], ignore_index=True)
lp2_n60.columns = ['instance','bs','time']
#lp2_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bs':lp2_n60['bs'].mean(),
    'time':lp2_n60['time'].mean()
    },index=[""]
)

lp2_n60 = pd.concat([lp2_n60,tab])
lp2_n60['instance'] = lp2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp2_n60

                              instance   bs      time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  1.350000
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  1.290000
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  1.430000
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  1.480000
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  1.290000
..                                 ...  ...       ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.510000
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.440000
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.470000
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.580000
                                resume  0.0  0.838167

[61 rows x 3 columns]

In [10]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60 = pd.DataFrame()
mip2_n60 = pd.concat([mip2_n60, df], ignore_index=True)
mip2_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip2_n60['bb'].mean(),
    'bs':mip2_n60['bs'].mean(),
    'gap':mip2_n60['gap'].mean(),
    'time':mip2_n60['time'].mean(),
    'nodes':mip2_n60['nodes'].mean(),
    'opt':mip2_n60['opt'].sum()
    },index=[""]
)

mip2_n60 = pd.concat([mip2_n60,tab])
mip2_n60['instance'] = mip2_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,8.000000,0.650000,3600.120000,733.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,11.000000,0.000000,2493.730000,1238.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,9.000000,0.000000,2077.130000,1791.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,13.000000,0.000000,2627.530000,852.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,9.000000,0.310000,3600.980000,1010.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,24.000000,5.000000,0.790000,3600.110000,1299.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,5.000000,0.770000,3600.670000,1423.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,27.000000,8.000000,0.700000,3600.010000,26260.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,27.000000,3.000000,0.890000,3600.490000,1230.000000,0
,resume,25.266667,7.783333,0.560667,3379.321167,5043.166667,8

In [11]:
form_ = "edge2"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip2_n60_p0 = pd.DataFrame()
mip2_n60_p0 = pd.concat([mip2_n60_p0, df], ignore_index=True)
mip2_n60_p0.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip2_n60_p0

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip2_n60_p0['bb'].mean(),
    'bs':mip2_n60_p0['bs'].mean(),
    'gap':mip2_n60_p0['gap'].mean(),
    'time':mip2_n60_p0['time'].mean(),
    'nodes':mip2_n60_p0['nodes'].mean(),
    'opt':mip2_n60_p0['opt'].sum()
    },index=[""]
)

mip2_n60_p0 = pd.concat([mip2_n60_p0,tab])
mip2_n60_p0['instance'] = mip2_n60_p0['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip2_n60_p0

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,0.00,1.000000,3600.110000,2659.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,1.00,0.910000,3600.130000,1434.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,1.00,0.890000,3600.010000,1415.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,1.00,0.920000,3600.100000,1401.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.00,0.920000,3600.010000,1889.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,23.000000,1.00,0.960000,3600.000000,19262.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,1.00,0.950000,3600.000000,28953.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,1.00,0.960000,3600.000000,31349.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.000000,1.00,0.960000,3600.010000,11537.000000,0
,resume,25.016667,0.95,0.940167,3600.025833,10395.883333,0

In [12]:
form_ = "edge3"
method_ = "lp"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

lp3_n60 = pd.DataFrame()
lp3_n60 = pd.concat([lp3_n60, df], ignore_index=True)
lp3_n60.columns = ['instance','bs','time']
#lp3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bs':lp3_n60['bs'].mean(),
    'time':lp3_n60['time'].mean()
    },index=[""]
)

lp3_n60 = pd.concat([lp3_n60,tab])
lp3_n60['instance'] = lp3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
lp3_n60

                              instance   bs    time
0    random_n60_k2_pos30_neg5_err5_1.g  0.0  1.5000
1    random_n60_k2_pos30_neg5_err5_2.g  0.0  1.4300
2    random_n60_k2_pos30_neg5_err5_3.g  0.0  1.7000
3    random_n60_k2_pos30_neg5_err5_4.g  0.0  1.6100
4    random_n60_k2_pos30_neg5_err5_5.g  0.0  1.4000
..                                 ...  ...     ...
56  random_n60_k5_pos30_neg5_err20_2.g  0.0  0.6100
57  random_n60_k5_pos30_neg5_err20_3.g  0.0  0.5000
58  random_n60_k5_pos30_neg5_err20_4.g  0.0  0.5400
59  random_n60_k5_pos30_neg5_err20_5.g  0.0  0.6600
                                resume  0.0  0.9345

[61 rows x 3 columns]

In [13]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60 = pd.DataFrame()
mip3_n60 = pd.concat([mip3_n60, df], ignore_index=True)
mip3_n60.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60['bb'].mean(),
    'bs':mip3_n60['bs'].mean(),
    'gap':mip3_n60['gap'].mean(),
    'time':mip3_n60['time'].mean(),
    'nodes':mip3_n60['nodes'].mean(),
    'opt':mip3_n60['opt'].sum()
    },index=[""]
)

mip3_n60 = pd.concat([mip3_n60,tab])
mip3_n60['instance'] = mip3_n60['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.00,23.0,0.000000,469.4200,28.000000,1
1,random_n60_k2_pos30_neg5_err5_2.g,11.00,11.0,0.000000,306.6100,7.000000,1
2,random_n60_k2_pos30_neg5_err5_3.g,9.00,9.0,0.000000,307.1600,3.000000,1
3,random_n60_k2_pos30_neg5_err5_4.g,13.00,13.0,0.000000,363.0100,7.000000,1
4,random_n60_k2_pos30_neg5_err5_5.g,13.00,13.0,0.000000,311.1600,9.000000,1
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,22.00,13.0,0.410000,3600.0100,3552.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.00,13.0,0.410000,3600.6200,1778.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.00,13.0,0.500000,3600.0200,10202.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,26.00,12.0,0.540000,3600.0100,2307.000000,0
,resume,23.75,17.0,0.173333,1592.4855,953.966667,38

In [14]:
form_ = "edge3"
method_ = "mip"

file=f"{method_}_n{n_}_{form_}_signed_presolve0.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

mip3_n60_p0 = pd.DataFrame()
mip3_n60_p0 = pd.concat([mip3_n60_p0, df], ignore_index=True)
mip3_n60_p0.columns = ['instance','bb','bs','gap','time','nodes','opt']
#mip3_n60_p0

tab = pd.DataFrame({
    'instance':"resume",
    'bb':mip3_n60_p0['bb'].mean(),
    'bs':mip3_n60_p0['bs'].mean(),
    'gap':mip3_n60_p0['gap'].mean(),
    'time':mip3_n60_p0['time'].mean(),
    'nodes':mip3_n60_p0['nodes'].mean(),
    'opt':mip3_n60_p0['opt'].sum()
    },index=[""]
)

mip3_n60_p0 = pd.concat([mip3_n60_p0,tab])
mip3_n60_p0['instance'] = mip3_n60_p0['instance'].str.replace('data/kmbs/RANDOM/random_','')
mip3_n60_p0

,instance,bb,bs,gap,time,nodes,opt
0,random_n60_k2_pos30_neg5_err5_1.g,23.000000,1.0,0.960000,3600.140,735.000000,0
1,random_n60_k2_pos30_neg5_err5_2.g,11.000000,2.0,0.820000,3600.030,710.000000,0
2,random_n60_k2_pos30_neg5_err5_3.g,9.000000,2.0,0.780000,3600.030,717.000000,0
3,random_n60_k2_pos30_neg5_err5_4.g,13.000000,0.0,1.000000,3600.020,90.000000,0
4,random_n60_k2_pos30_neg5_err5_5.g,13.000000,1.0,0.920000,3600.020,714.000000,0
...,...,...,...,...,...,...,...
56,random_n60_k5_pos30_neg5_err20_2.g,23.000000,2.0,0.910000,3600.070,1362.000000,0
57,random_n60_k5_pos30_neg5_err20_3.g,22.000000,2.0,0.910000,3600.000,3207.000000,0
58,random_n60_k5_pos30_neg5_err20_4.g,26.000000,2.0,0.920000,3600.030,1604.000000,0
59,random_n60_k5_pos30_neg5_err20_5.g,27.000000,2.0,0.930000,3600.040,1164.000000,0
,resume,24.833333,1.5,0.883167,3547.032,1803.433333,1

In [ ]:
mip1_n60['instance'] = mip1_n60['instance'].str.replace('_','\_') 
print(mip1_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

In [ ]:
mip2_n60['instance'] = mip2_n60['instance'].str.replace('_','\_') 
print(mip2_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

In [ ]:
mip3_n60['instance'] = mip3_n60['instance'].str.replace('_','\_') 
print(mip3_n60[['instance','bs','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))